# Generated by Django 6.0.6 on 2026-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
